### ISSUE TITLE
Integration not showing up after installing

### ISSUE THREAD

**Issue by rvanarkel** [travisghansen/hass-pfsense#1]
Hi,

I installed the Hass-Pfsense integration in HACS. But after restarting the server I don't see the integration anywhere.
In the readme it says 'Configuration is managed entirely from the UI using config_flow semantics.' so i expected the integration under configuration->Integrations.
Also when i try to add in manually it can't find it in the list.

I checked the log of Home assistant and the only event with a reference to pfSense is this:
2021-10-21 16:31:12 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pfsense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by orcema** [comment]
i figured it out, on the HACS integration page, have to click on the 3 dots and add the git repository address.

<img width="162" alt="Screenshot 2021-10-21 at 22 55 30" src="https://user-images.githubusercontent.com/12600222/138355690-9fc113f7-981e-46f1-a1c0-daca5e261e72.png">

**Comment by travisghansen** [comment]
Awesome! Hopefully soon it will be included by default. Would love any feedback you can provide after getting it setup.
