### ISSUE TITLE
[FR] Get this baby in the HACS integrations!

### ISSUE THREAD

**Issue by HeedfulCrayon** [travisghansen/hass-pfsense#10]
Wow, this integration is awesome! I've been looking for something like this for a while and was using the telegraf plugin on pfsense, but it didn't quite have everything I wanted. This integration has exactly what I need.
With that said, you should get this published in the HACS store so that it is more easily discovered.

**Comment by travisghansen** [comment]
https://github.com/hacs/default/pull/1117
