### ISSUE TITLE
Feature request - renew WAN address

### ISSUE THREAD

**Issue by Mastiffen** [travisghansen/hass-pfsense#106]
I have a problem with my setup. Our IPTV sometimes stops working, and renewing the WAN is the only way to get it up and running again. I’d love it if that could be done from Hass, because then I could easily tie that to a Z-Wave switch, so my wife could do it without me explaining every time how to log on to the pfSense box and so on. So a service or even a switch that renews the WAN address would be a great feature.

**Comment by travisghansen** [comment]
Share with me the exact steps you take in the gui and then I can look through the code to see what it's doing. After that it will probably be pretty simple to invoke a service which does the trick.

**Comment by Mastiffen** [comment]
Great, thanks a lot! It's very simple: Status, Interfaces, click Release WAN, click "yes" on "are you sure you want to release WAN", wait around five seconds until the button turns into "Renew WAN", click that and then a similiar popup warning. Done.

**Comment by travisghansen** [comment]
Try something like this:

```
service: pfsense.exec_php
data:
  entity_id: binary_sensor.pfsense_localdomain_pending_notices_present
  script: |
    require_once '/etc/inc/interfaces.inc';
    
    $if = "igb0";
    $interface = "wan";
    $ifdescr = "WAN";
    $ipv = 4;
    $sleep = 1;
        
    // Copied from: /usr/local/www/status_interfaces.php
    // Relinquish the DHCP lease from the server.
    // $if is physical interface: ie: igb0
    // $ifdescr is WAN, LAN, etc
    // $ipv is '4' or '6'
    function dhcp_relinquish_lease($if, $ifdescr, $ipv) {
            $leases_db = '/var/db/dhclient.leases.' . $if;
            $conf_file = '/var/etc/dhclient_'.$ifdescr.'.conf';
            $script_file = '/usr/local/sbin/pfSense-dhclient-script';
            $ipv = ((int) $ipv == 6) ? '-6' : '-4';

            if (file_exists($leases_db) && file_exists($script_file)) {
                    mwexec('/usr/local/sbin/dhclient {$ipv} -d -r' .
                            ' -lf ' . escapeshellarg($leases_db) .
                            ' -cf ' . escapeshellarg($conf_file) .
                            ' -sf ' . escapeshellarg($script_file));
            }
    }
    
    dhcp_relinquish_lease($if, $ifdescr, $ipv);
    interface_bring_down($interface);
    sleep($sleep);
    interface_configure($interface);
    
    // reload services, etc here as necessary
    $toreturn = [
        "data" => true,
    ];\
```

be sure to modify these to your needs:

```
    $if = "igb0";
    $interface = "wan";
    $ifdescr = "WAN";
    $ipv = 4;
    $sleep = 1;
```

I don't have any machines using dhcp so it's untested but should work (or will work after we get the weird name/descriptions stuff aligned how pfsense wants it.

**Comment by Mastiffen** [comment]
Wow! I'm so sorry, I didn't know there was an answer in this one! :O I did not mean to "ghost" it or you, after all this is something I really want!

I tried it now, and it worked right out of the box! The only thing I had to change was the name (of course...). I also changed the sleep to 5, just to make sure it really renewed, and now I just have to wait for the next time the IPTV messes up, so I can test it. Thank you very much for the help!

**Comment by travisghansen** [comment]
Great! If you’re willing and get it tested out it would be great to add it to the EXEC_EXAMPLES.md file so others can reference it.

**Comment by Mastiffen** [comment]
Feel free to add it, of course! It works as it should, renewing the WAN, it's just our IPTV problem that I need to test it on, but that's so specific that nobody else will need it.

**Comment by travisghansen** [comment]
You'd be surprised how many people need to release/renew for various reasons!

**Comment by Mastiffen** [comment]
Actually that's not what I meant. :) I meant that I have tested the release/renew, and it works as it should, renewing the WAN. It's only the IPTV part of this equation that's something I don't think anybody else will ever need.
