### ISSUE TITLE
CPU Frequency shows 'Unavailable'

### ISSUE THREAD

**Issue by bearhntr** [travisghansen/hass-pfsense#109]
@travisghansen  - so far (just installed this today) - loving this over the UPnP/IGD I was using.  Awesome work!!!

Any ideas why I am seeing this?  (see image)  --  The pfSense is installed on an HP T620 Plus ThinClient using their 'bootable ISO' to install directly on the machine (no Docker or Container done by me under another OS)  - It is not shown (specifically in pfSense (other 2 images) - just wondering if I need to do something. 

![image](https://user-images.githubusercontent.com/100164602/195411664-dcdeb02c-3b73-41c2-8b7f-99ce6d877a91.png)

**Here is what I see in pfSense:**

![image](https://user-images.githubusercontent.com/100164602/195411987-7642a9d2-6401-469c-a24e-288f3a2f4044.png)

![image](https://user-images.githubusercontent.com/100164602/195412087-12e9bf4a-5e9f-4385-9818-3c55852189ef.png)

**Comment by travisghansen** [comment]
Welcome! Some systems/processors simply don’t have that information. If you don’t see the cpu data on the pfSense dashboard then it won’t show in the integration either as I use the same mechanism to get the data. Do you ever see the frequency on the dashboard in your screenshot?

**Comment by bearhntr** [comment]
@travisghansen --

  I do not see anything in pfSense which is specifically called "CPU Frequency" only the speed of the CPU.  Also since I moved pfSense to PROXMOX - no matter what I do, I cannot get pfSense to show me the CPU Temp either.  Even thought IOMMU is enabled and the PCI Sensor is added to the VM.

**Comment by EuleMitKeule** [comment]
Such cases should be handled by returning a state of `None` instead of `unavailable` since this indicates the user that there is some kind of connection or configuration problem which there isn't.

**Comment by travisghansen** [comment]
That's fair. I'll look into it.
