### ISSUE TITLE
Feature request - DNS Resolver service status 

### ISSUE THREAD

**Issue by Dinth** [travisghansen/hass-pfsense#120]
Hi. Im DNS Resolver is often crashing (probably not enough RAM) and i need to manually restart it. I would love to give other housemembers ability to restart it (or at least check its status) from within HA, without risking to give them access to the whole router. Would it be possible to implement this in the integration?

**Comment by travisghansen** [comment]
There should be a switch yes (they are disabled by default).

**Comment by jannesaarinen** [comment]
@Dinth See https://github.com/pfsense/FreeBSD-ports/commits/devel/sysutils/pfSense-pkg-Service_Watchdog. You can install it from pfSense package manager. It monitors automatically the service on pfSense and restarts those if it sees they are down.

**Comment by Dinth** [comment]
many thanks!
