### ISSUE TITLE
Feature request - Custom  port number for HTTPS connection

### ISSUE THREAD

**Issue by ihelland** [travisghansen/hass-pfsense#121]
When using HAProxy it is common to reserve port 443 for external domains and therefore change the pfSense GUI port to another port number. Is it somehow possible to specify/override the port number that this integration uses? Thanks for an otherwise great and useful integration! 👍

**Comment by travisghansen** [comment]
Sure, just add the port to the url.

**Comment by ihelland** [comment]
> Sure, just add the port to the url.

Thanks! That worked well. 😊

**Comment by travisghansen** [comment]
Great!
