### ISSUE TITLE
Compatibility with PfSense 2.7.0 alpha

### ISSUE THREAD

**Issue by woodsb02** [travisghansen/hass-pfsense#123]
I've recently updated from PfSense 2.6.0 to the devel snapshot 2.7.0.a.20221206.0600.

I started receiving error notifications in the Pfsense web interface every 30 seconds with the message below.
```
PHP ERROR: Type: 1, File: /etc/inc/util.inc, Line: 220, Message: Uncaught TypeError: flock(): supplied resource is not a valid stream resource in /etc/inc/util.inc:220
Stack trace:
#0 /etc/inc/util.inc(220): flock(Resource id #11, 3)
#1 /usr/local/www/xmlrpc.php(990): unlock(Resource id #11)
#2 {main}
  thrown
```

Once I disabled the hass-pfsense integration in home assistant, I stopped receiving these errors. I suspect there is a compatibility issue with the new version of pfsense, that might require some changes to this hass-Pfsense plugin.

To try and assist debugging this, please see below extracts from the Pfsense files in the stack trace (with a few lines of context preceding the trouble lines):

/etc/inc/util.inc (lines 217-220):
```
/* unlock configuration file */
function unlock($cfglckkey = 0) {
	if (!is_null($cfglckkey)) {
		@flock($cfglckkey, LOCK_UN);
```

/usr/local/www/xmlrpc.php (Lines 976-990):
```

$xmlrpclockkey = lock('xmlrpc', LOCK_EX);

XML_RPC2_Backend::setBackend('php');
$HTTP_RAW_POST_DATA = file_get_contents('php://input');

$options = array(
	'prefix' => 'pfsense.',
	'encoding' => 'utf-8',
	'autoDocument' => false,
);

$server = XML_RPC2_Server::create(new pfsense_xmlrpc_server(), $options);
$server->handleCall();

unlock($xmlrpclockkey);
```

**Comment by travisghansen** [comment]
I’m sure it can be fixed but it will be a little while before I can take a look.

**Comment by w1tw0lf** [comment]
I can confirm the issue, as I am experiencing the exact same issue.

**Comment by davericher** [comment]
Likewise, it seems downgrading Pfsense is not as simple as I imagined it to be 👎

**Comment by travisghansen** [comment]
I’ll probably have some time in the next week or so to take a look.

**Comment by travisghansen** [comment]
Can someone edit line 173 in `/etc/inc/util.inc` and change the following line:

```
FROM
if (!is_null($cfglckkey)) {

TO
if (!is_null($cfglckkey) && is_resource($cfglckkey)) {
```

Probably best to restart after but it may work without a restart. I want to know if there are any other bugs/issues.

**Comment by davericher** [comment]
> Can someone edit line 173 in `/etc/inc/util.inc` and change the following line:
> 
> ```
> FROM
> if (!is_null($cfglckkey)) {
> 
> TO
> if (!is_null($cfglckkey) && is_resource($cfglckkey)) {
> ```
> 
> Probably best to restart after but it may work without a restart. I want to know if there are any other bugs/issues.

That does resolve the lock file issue, however 
``` PHP ERROR: Type: 1, File: /usr/local/www/xmlrpc.php(147) : eval()'d code, Line: 14, Message: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/www/xmlrpc.php(147) : eval()'d code:14
Stack trace:
#0 /usr/local/www/xmlrpc.php(147): eval()
#1 /usr/local/share/pear/XML/RPC2/Server/CallHandler/Instance.php(141): pfsense_xmlrpc_server->exec_php('\nini_set('displ...')
#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Server_Callhandler_Instance->__call('pfsense.exec_ph...', Array)
#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()
#4 /usr/local/www/xmlrpc.php(988): XML_RPC2_Backend_Php_Server->handleCall()
#5 {main}
thrown @ 2023-01-15 15:06:11
PHP ERROR: Type: 1, File: /usr/local/www/xmlrpc.php(147) : eval()'d code, Line: 14, Message: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/www/xmlrpc.php(147) : eval()'d code:14
Stack trace:
#0 /usr/local/www/xmlrpc.php(147): eval()
#1 /usr/local/share/pear/XML/RPC2/Server/CallHandler/Instance.php(141): pfsense_xmlrpc_server->exec_php('\nini_set('displ...')
#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Server_Callhandler_Instance->__call('pfsense.exec_ph...', Array)
#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()
#4 /usr/local/www/xmlrpc.php(988): XML_RPC2_Backend_Php_Server->handleCall()
#5 {main}
thrown @ 2023-01-15 15:06:22``` 

Does not look like we are out of the water yet. Seems to be an eval line So I am thinking maybe the plugin is using something that was deprecated in PHP 8.

**Comment by travisghansen** [comment]
I've just done a fresh install of using the latest 2.7 and it works out of the box without any hacks at all. I'm wondering if there is some specific package that's causing the issue. What extras do you have installed?

**Comment by woodsb02** [comment]
On the box where I am experiencing the problem I have the following packages installed:
Acme, Avahi, iperf, lldpd, nmap, ntopng, status_traffic_totals, telegraf, WireGuard.

I also wonder if it could be a feature of upgrading - if installing those packages doesn’t help, it might be worth installing pfsense 2.6, integrating with home assistant, and then upgrading.

I’m also using a non-admin user with the System - HA node sync privilege - in case that has anything to do with it.

**Comment by travisghansen** [comment]
I installed all those packages and used a non-admin/non-root user and still no errors :(

I may need someone to message me privately and let me run some api calls directly against their firewall or do that themselves to see where the failure is :(

**Comment by davericher** [comment]
If you want to provide some calls I can run I would more than happy to assist.

**Comment by spyfly** [comment]
Also getting these errors with the pfSense+ 23.01 BETA.

``` 
PHP ERROR: Type: 1, File: /etc/inc/util.inc, Line: 174, Message: Uncaught TypeError: flock(): supplied resource is not a valid stream resource in /etc/inc/util.inc:174
Stack trace:
#0 /etc/inc/util.inc(174): flock(Resource id #10, 3)
#1 /usr/local/www/xmlrpc.php(990): unlock(Resource id #10)
#2 {main}
```

**Comment by travisghansen** [comment]
I’ll see if I can add some better logging. If not someone will need to setup a python dev env and start running through all the calls to see which is making it crash.

**Comment by travisghansen** [comment]
Does anyone have corresponding logs from hass?

**Comment by travisghansen** [comment]
I just released `v0.5.11`. Try it out and see if you get something logged into the hass logs now. The primary purpose is to figure out which method(s) is causing the error to begin with. Usually when I know which method it is I can add necessary robustness around the code to handle any possible edge cases.

**Comment by travisghansen** [comment]
Those are both pretty low level errors I am not sure the integration can solve. It appears you have some connectivity issues at a fundamental level. Having said that, that doesn’t explain why you would have related php errors on pfsense…

**Comment by travisghansen** [comment]
Checkout the project and then do the following:

```
[[ ! -f "venv/bin/activate" ]] && virtualenv venv || true
source venv/bin/activate
pip install --upgrade -r requirements_dev.txt
```

Then create a file in the root of project called `api.py`

```
import os
import sys
import json

from custom_components.pfsense.pypfsense import Client

url      = os.environ.get("PFSENSE_URL")
username = os.environ.get("PFSENSE_USERNAME")
password = os.environ.get("PFSENSE_PASSWORD")

client = Client(url, username, password, {"verify_ssl": False})

#print(client.get_services())
#print(json.dumps(client.get_carp_interfaces()))
#print(client.get_carp_status())
```

Set the env vars as appropriate and then run `python api.py` commenting out the method you want to invoke. You can see what methods the integration invokes here: https://github.com/travisghansen/hass-pfsense/blob/main/custom_components/pfsense/__init__.py#L316-L345

Basically you'll need to turn off the integration in hass, clear the error log in pfsense, and then start going through the methods 1 at a time until you find whatever is causing the spam :(

**Comment by spyfly** [comment]
So it seems like
```
print(client.get_services()) # Creates 9 Errors every run
print(json.dumps(client.get_carp_interfaces())) # Creates 1 Error every run
print(client.get_carp_status()) # Creates 1 Error every run
```

I believe this is a more general issue in the way the calls are made.

**Comment by travisghansen** [comment]
Did other calls produce no errors? And which error(s) did the mentioned calls produce?

**Comment by travisghansen** [comment]
This seems to have been cleaned up in more recent versions..

```
function unlock($cfglckkey = 0)
{
        if (!is_resource($cfglckkey))
                return;
...
```

**Comment by spyfly** [comment]
Seems to work now without issues
