### ISSUE TITLE
this add-on keeps becoming unavailable

### ISSUE THREAD

**Issue by tung256** [travisghansen/hass-pfsense#124]
i gave this add-on the admin login account to be sure i have all the rights.
however, the add on and devices it tracks keep becoming unavailable.  any idea why?

![image](https://user-images.githubusercontent.com/37672036/206566956-9e6806b7-e8a6-4c85-b849-57cf3600799d.png)

![image](https://user-images.githubusercontent.com/37672036/206567093-65823ef0-9a56-49c1-a304-7ee74567731b.png)

**Comment by travisghansen** [comment]
hass logs would be helpful. Each scan interval the integration gathers up a whole bunch of info for all the sensors, so my guess is that it’s hitting some timeout/error causing it to make everything go unavailable at the same time.

**Comment by tung256** [comment]
which logs would you like to be exact?
![image](https://user-images.githubusercontent.com/37672036/207753589-8b2343be-d107-4295-85fa-dfccfe4077e2.png)

**Comment by travisghansen** [comment]
Yeah the hass logs, the top entry.
