### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [travisghansen/hass-pfsense#127]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by travisghansen** [comment]
Thanks @frenck! I usually work on this integration in waves so the next round of updates I’ll be sure to migrate to the new style.

**Comment by frenck** [comment]
No rush! Thanks, @travisghansen 👍 

../Frenck

**Comment by travisghansen** [comment]
Curious do you actually use this or was this generated from automated data based off of `hacs` or similar?

**Comment by frenck** [comment]
No, I'm not using custom integrations myself. However, I am a maintainer of the Home Assistant Core.

When making decisions on things like deprecations (or breaking changes), it is really helpful to have insights into things like the usage of functionalities (or, in this case, constants).

I, therefore, have a local checkout of every custom integration I can find/know of, allowing me to query everything out there easily.

For this specific case, we can't generate warnings in Home Assistant, so as an experiment, I have manually raised 100 issues across many custom integrations. To see how the response, in general, would be.

So far, the responses have been good, and the larger part of all issues I've raised have been resolved and closed already.

../Frenck

**Comment by travisghansen** [comment]
Yeah I know who you are! I follow and admire your work :)

**Comment by travisghansen** [comment]
I think I've got them all removed in this: https://github.com/travisghansen/hass-pfsense/commit/978db5ea46f6d4b3ab2ae8995a0ad35ae7818133

In `main` and `v0.5.12`.

**Comment by frenck** [comment]
Thanks for addressing it! 👍 

../Frenck
