### ISSUE TITLE
unable to start service

### ISSUE THREAD

**Issue by M0WGF** [travisghansen/hass-pfsense#129]
Hi I have a switch configured to start and top the openvpn service however it's not working and ideas as I've followed the documentation.  

  - platform: template
    switches:
      pfsense_openvpn_control:
        turn_on:
          service: pfsense.start_service
          data:
            entity_id: binary_sensor.pfsense_home_arpa_pending_notices_present
            service_name: "openvpn"
        turn_off:
          service: pfsense.stop_service
          data:
            entity_id: binary_sensor.pfsense_home_arpa_pending_notices_present
            service_name: "openvpn"

interestingly pfsense.send_wol works fine.

**Comment by M0WGF** [comment]
Should have mentioned it also starts and stop the sshd daemon fine.

**Comment by travisghansen** [comment]
Yeah the openvpn services are special because it’s actually a service per config (server or client). I’m not sure what it would take to make that transparent to hass/integration to create a switch per config. In the meantime you could use the exec_php hass service to restart and/or do whatever you need.

**Comment by M0WGF** [comment]
thanks I'll give that ago

**Comment by travisghansen** [comment]
I just released `v0.6.0` which has proper support for openvpn switches. Update and enable the new switches and it should 'just work'.

**Comment by M0WGF** [comment]
Brilliant thank you for letting me know.

**Comment by travisghansen** [comment]
Give it a test and let me know if it works. If so we'll close this down.

**Comment by M0WGF** [comment]
Will do it maybe a week before I get back to you as I haven't the VPN installed at the moment.

**Comment by M0WGF** [comment]
After saying it would take me week I had half hour spare this evening and I can confirm this update turns the VPN service on and off successfully.   Many thanks for doing this it is very much appreciated 👍

**Comment by travisghansen** [comment]
Great! Thanks for the patience ;)
