### ISSUE TITLE
Can not connect integration?

### ISSUE THREAD

**Issue by akballow** [travisghansen/hass-pfsense#130]
Hey not sure what the issue is but I can not even connect to my pfsense device.

Using the same details in the web browser I can log in fine. 

Please advise on how I can troubleshoot this. I already disabled pfctl -d 

![Screenshot 2023-01-16 at 12 37 28 PM](https://user-images.githubusercontent.com/2824631/212762118-22311420-2b90-4397-acf7-093467a842a2.png)

**Comment by travisghansen** [comment]
Any logs on the pfsense box that help? What version of pfsense are you running?

**Comment by akballow** [comment]
No logs it is as if it never reaches it pfsense 2.6.0. I can reach the info from the HA console directly

**Comment by akballow** [comment]
Log Details (ERROR)


 
This error originated from a custom integration.
Logger: custom_components.pfsense.config_flow
Source: custom_components/pfsense/config_flow.py:142 
Integration: pfSense ([documentation](https://github.com/travisghansen/hass-pfsense), [issues](https://github.com/travisghansen/hass-pfsense/issues)) 
First occurred: 9:50:16 PM (3 occurrences) 
Last logged: 9:59:54 PM

Unexpected err=ConnectionRefusedError(111, 'Connection refused'), type(err)=<class 'ConnectionRefusedError'>
Unexpected err=gaierror(-2, 'Name does not resolve'), type(err)=<class 'socket.gaierror

**Comment by akballow** [comment]
What would cause connection refused when it works via curl from the console of the same machine?

**Comment by travisghansen** [comment]
What is the url you use to access pfsense via a browser? Seems to me you have a fundamental networking issue going on :(

**Comment by akballow** [comment]
Sorry i am an idiot i had a static arp problem. All is well great integration!

**Comment by travisghansen** [comment]
Great!
