### ISSUE TITLE
Request: Support read-only access for non-admin users

### ISSUE THREAD

**Issue by flobernd** [travisghansen/hass-pfsense#131]
Hi there,

would it be possible to support non-admin users (as well without the "HA node sync" privilege that effectively grants admin privileges) for a purely read-only integration?

I don't feel very comfortable granting admin privileges and my usecase is only about displaying upload/download statistics.

**Comment by travisghansen** [comment]
It’s not really possible no. The api the integration uses as a base will not allow access without that permission.

**Comment by flobernd** [comment]
That's unfortunate :/ Thanks for the fast response anyways!
