### ISSUE TITLE
Error switching on/off forward rule

### ISSUE THREAD

**Issue by magtimmermans** [travisghansen/hass-pfsense#132]
I have an error when I start an automation switch on a nat port forward rule on or off.

This is the message. Hopefully, you can fix this easily.

Thanks

  File "/config/custom_components/pfsense/switch.py", line 326, in async_turn_on
    await self.hass.async_add_executor_job(method, tracker)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 302, in enable_nat_port_forward_rule_by_created_time
    if rule["created"]["time"] != created_time:
KeyError: 'created'

and

  File "/config/custom_components/pfsense/switch.py", line 326, in async_turn_on
    await self.hass.async_add_executor_job(method, tracker)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense/pypfsense/__init__.py", line 302, in enable_nat_port_forward_rule_by_created_time
    if rule["created"]["time"] != created_time:
KeyError: 'created'

**Comment by travisghansen** [comment]
How old is you installation and more specifically how long have the nat rules been around? I think the created time is used as a sort of key/id for the rules so those must exist to function properly. Seems like something more egregious is at play here than the logs are indicating on the surface.

**Comment by magtimmermans** [comment]
I have look into this a bit deeply. The filter rules are working fine and the error is only on the NAT pot forward rule. How can I look into this more deeply.  I suppose you use the epoch creation date of the rule as a key. So for some reason this created var is empty or so?  I am not sure how you get this creation date using xmlrpc. Can I simulate this call with postman?  I am very bad in python scripts.

**Comment by travisghansen** [comment]
My guess is some odd rules don’t have a created time for some reason. I can probably add a more robust check and go from there…or if you’re comfortable hacking the code locally I can send a diff for you to try.

**Comment by travisghansen** [comment]
Try `v0.5.9`: https://github.com/travisghansen/hass-pfsense/commit/4a7209d156030a18dbc3df506b52c1add665394d

**Comment by magtimmermans** [comment]
That fixed it! :) Thank you very much! You can release this.
