### ISSUE TITLE
Protocol Error, Retrying setup

### ISSUE THREAD

**Issue by calibrae** [travisghansen/hass-pfsense#133]
Hi,

Sorry if I'm duplicating an existing issue, I did try to find some related without success.

When I start the integration, I get this log message in HA

`Config entry 'calisense' for pfsense integration not ready yet: <ProtocolError for hass:vNUUQDQZbnWW8nk@10.11.0.1/xmlrpc.php: 500 Internal Server Error>; Retrying in background`

And this log entries in pfsense

`

Jan 19 17:59:08 | php-fpm | 93956 | thrown
-- | -- | -- | --
Jan 19 17:59:08 | php-fpm | 93956 | #5 {main}
Jan 19 17:59:08 | php-fpm | 93956 | #4 /usr/local/www/xmlrpc.php(988): XML_RPC2_Backend_Php_Server->handleCall()
Jan 19 17:59:08 | php-fpm | 93956 | #3 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()
Jan 19 17:59:08 | php-fpm | 93956 | #2 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135):  XML_RPC2_Server_Callhandler_Instance->__call('pfsense.exec_ph...',  Array)
Jan 19 17:59:08 | php-fpm | 93956 | #1  /usr/local/share/pear/XML/RPC2/Server/CallHandler/Instance.php(141):  pfsense_xmlrpc_server->exec_php('\nini_set('displ...')
Jan 19 17:59:08 | php-fpm | 93956 | #0 /usr/local/www/xmlrpc.php(147): eval()
Jan 19 17:59:08 | php-fpm | 93956 | Stack trace:
Jan 19 17:59:08 | php-fpm | 93956 | /xmlrpc.php: New alert found: PHP ERROR: Type: 1, File:  /usr/local/www/xmlrpc.php(147) : eval()'d code, Line: 14, Message:  Uncaught TypeError: Cannot access offset of type string on string in  /usr/local/www/xmlrpc.php(147) : eval()'d code:14

`

I'm more than willing to help fix this, I can easily replicate my pfsense install for tinkering.

Thanks for your help.

**Comment by travisghansen** [comment]
Usually this is connected to credentials missing proper permissions. Are you using `admin` user or a dedicated user created for the integration?

**Comment by calibrae** [comment]
Dedicated user, with the HA node sync permission. 
I tried adding the user to the admin group, and removing it from, does not change a thing.

**Comment by travisghansen** [comment]
Can you try with `admin` creds to rule out that as being the issue?

**Comment by calibrae** [comment]
Same thing. I had a doubt about the password since I use a "?" character in the password and it was html encoded. But even without the ? I get the same "Protocol Error" issue.
I'm on a 2.7-devel version.

**Comment by travisghansen** [comment]
Is the integration actually created and in an active state, or does it never get created?

**Comment by travisghansen** [comment]
Also, it's a longshot but can you try `v0.5.10`?

**Comment by calibrae** [comment]
With the latest 0.5.11 the integration timeout at first connection. 
And pfsense detects a crash 
`PHP Errors:
[22-Jan-2023 11:10:01 Europe/Paris] PHP Fatal error:  Uncaught TypeError: flock(): supplied resource is not a valid stream resource in /etc/inc/util.inc:174
Stack trace:
#0 /etc/inc/util.inc(174): flock(Resource id #10, 3)
#1 /usr/local/www/xmlrpc.php(990): unlock(Resource id #10)
#2 {main}
  thrown in /etc/inc/util.inc on line 174`

**Comment by travisghansen** [comment]
What version of pfsense? Can you send over the hass logs as well?

**Comment by PhilipJayyFry** [comment]
I am having the same issue as well. Been trying the main admin account. Not quite sure whats going on..
v0.5.15
2.4.4-RELEASE-p2 (amd64) 

Pfsense keeps throwing this up:
PHP ERROR: Type: 1, File: /usr/local/www/xmlrpc.php(140) : eval()'d code, Line: 19, Message: Uncaught Error: Call to undefined function system_get_dhcpleases() in /usr/local/www/xmlrpc.php(140) : eval()'d code:19
Stack trace:
#0 /usr/local/www/xmlrpc.php(140): eval()
#1 /usr/local/share/pear/XML/RPC2/Server/CallHandler/Instance.php(141): pfsense_xmlrpc_server-&gt;exec_php('\nini_set('displ...')
#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Server_Callhandler_Instance-&gt;__call('pfsense.exec_ph...', Array)
#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server-&gt;getResponse()
#4 /usr/local/www/xmlrpc.php(768): XML_RPC2_Backend_Php_Server-&gt;handleCall()
#5 {main}
thrown @ 2023-01-29 23:29:41

**Comment by travisghansen** [comment]
2.4.4 is pretty old. Dev was done against 2.5.2 and 2.6.0 was released a year ago. Update and I think your issues will go away.

**Comment by PhilipJayyFry** [comment]
Well my pfSense crashed during the update but the integration started working after I got it set up again. Thanks!
