### ISSUE TITLE
Have changelog available in HACS

### ISSUE THREAD

**Issue by HermesHonshappo** [travisghansen/hass-pfsense#138]
Hello

Is it possible to have the changelog info populated to HACS?
Up to now, I see that the version has been bumped 5 times, but no idea why.

<img width="400" alt="Screenshot 2023-01-31 at 10 50 33" src="https://user-images.githubusercontent.com/97752752/215726704-16692d71-ab14-4dfa-afb1-0d92d1b0e5ef.png">

The info seems to be available, at least in the github release page: https://github.com/travisghansen/hass-pfsense/releases

I know it's cosmetic, but I'd like to know why I'm updating without having to go to github each time

**Comment by travisghansen** [comment]
Yeah, it's just maintaining the data in a couple places. I don't recall exactly where hacs wants the data but it's obviously possible.

**Comment by travisghansen** [comment]
I'll try to keep them updated moving forward. I've added the notes for the past couple releases.
