### ISSUE TITLE
Get CPU data of PFSense running in proxmox

### ISSUE THREAD

**Issue by ashoktvm** [travisghansen/hass-pfsense#143]
Is there any way to get the CPU data of the PFSense firewall running inside in proxmox?

**Comment by travisghansen** [comment]
Not really. If pfsense adds support and you see the cpu details in the pfsense gui then it will likely show up in hass/api.

**Comment by ashoktvm** [comment]
Thanks for the reply. So have to find another way to get those data

**Comment by travisghansen** [comment]
Maybe a proxmox integration/plugin?

**Comment by ashoktvm** [comment]
Proxmox doesn't provide the CPU temperature of VM

**Comment by travisghansen** [comment]
A vm cpu doesn’t have a temperature :) if you’re after the temp of the host cpu then there are various ways to get that into hass. I think proxmox does have stats for cpu usage of the vm right?

**Comment by ashoktvm** [comment]
> A vm cpu doesn’t have a temperature :) if you’re after the temp of the host cpu then there are various ways to get that into hass. I think proxmox does have stats for cpu usage of the vm right?

Yes I need host temperature. Can you point me to a direction where I will be able to get the correct temperature of proxmox host to HASS?

**Comment by travisghansen** [comment]
Don't think that's possible. Even if you pass host cpu through I don't think you get those sensors but I could be wrong.
