### ISSUE TITLE
Integration died with update to 2023.5 beta

### ISSUE THREAD

**Issue by cmurphy1021** [travisghansen/hass-pfsense#158]
Logger: homeassistant.setup
Source: setup.py:214
First occurred: 10:04:50 PM (1 occurrences)
Last logged: 10:04:50 PM

Setup failed for custom integration pfsense: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

![image](https://user-images.githubusercontent.com/108307758/235051059-b1a5dfef-65b6-4512-ad66-a3afb66b2fae.png)

**Comment by dharvey242** [comment]
Same here.

**Comment by AnnabellaRenee87** [comment]
Can confirm, restoring a backup restores functionality.

**Comment by travisghansen** [comment]
Fixed here: https://github.com/travisghansen/hass-pfsense/commit/6a835fe45d0adb9e8f710544ad45287591c3ec1e
