### ISSUE TITLE
Upstream component to Home Assistant

### ISSUE THREAD

**Issue by alistair23** [travisghansen/hass-pfsense#187]
Have you looked at upstreaming this to HA Core?

It seems like this is missing tests, otherwise it should be straight forward to meet the [requirements](https://developers.home-assistant.io/docs/development_checklist/)

**Comment by travisghansen** [comment]
Not really no :( my time for this is quite limited atm. If the core devs would like to pull it in and take ownership I am open to that for sure but the timing isn't great for me to take that on currently.
