### ISSUE TITLE
Entities remain unavailable despite enabled status

### ISSUE THREAD

**Issue by orcema** [travisghansen/hass-pfsense#2]
<img width="1413" alt="Screenshot 2021-10-21 at 23 14 12" src="https://user-images.githubusercontent.com/12600222/138359170-33427a90-9e59-4b44-a578-e93eb25c9cb8.png">

**Comment by travisghansen** [comment]
It appears to simply be a UI issue where the UI doesn't refresh on that specific page. Leave that page and come back and you should see it properly (I just tried with that exact service).

**Comment by orcema** [comment]
This morning it work for me too but i didn't touch anything in the meanwhile, thus i guess it should have been a refresh issue as you mentionned.

<img width="1409" alt="Screenshot 2021-10-22 at 06 35 42" src="https://user-images.githubusercontent.com/12600222/138394196-f1a1134d-f9aa-4cf2-9581-e3833c1cde33.png">
