### ISSUE TITLE
Start using releases

### ISSUE THREAD

**Issue by rokam** [travisghansen/hass-pfsense#27]
It would be great if you start using releases to deliver updates. Otherwise, all changes in repo, like readme/docs should ship a new version to home assistant.

**Comment by travisghansen** [comment]
Yeah I will. Does that just work with hacs if I simply create a git tag?

**Comment by firstof9** [comment]
I _think_ you have to do an actual release for it to work with HACS.

**Comment by rokam** [comment]
I think @firstof9 is right.

**Comment by travisghansen** [comment]
Just created `v0.1.0`. Can you confirm it works as designed in hacs?

**Comment by rokam** [comment]
![image](https://user-images.githubusercontent.com/2856518/141199413-d98c4992-ba0d-40b4-bbc0-6b88daef73ab.png)

That's perfect.

**Comment by travisghansen** [comment]
Great, will publish using that in the future for sure!

**Comment by travisghansen** [comment]
Tambem falo portugues! :D
