### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by vanimox** [travisghansen/hass-pfsense#29]
Good afternoon, 

After installing Pfsense, I get the error "Config flow could not be loaded" when attempting to add the configuration through Configuration > Integrations. 

I'm incredibly excited about this integration you've created and any assistance you might be able to provide would be incredibly appreciated! Thank you!

**Comment by travisghansen** [comment]
Welcome! Make sure to do a hard refresh of the browser/ui (you can try in incognito alternatively).

If that still fails send over the hass logs for me to take a look.
