### ISSUE TITLE
No configuation options

### ISSUE THREAD

**Issue by withanhdammit** [travisghansen/hass-pfsense#3]
I just installed this component (custom repository via HACS) and when I search the integrations list, it does not show.  I can see it in the custom_components folder, so I believe I connected the repository and installed it correctly.

How to I activate this integration?

**Comment by withanhdammit** [comment]
I opened in incognito mode and it's there.  Tried a hard refresh and I'm good to go.

Thanks so much for responding so quickly!  That is highly appreciated!  Do you have a donation link or anything like that?  I'd like to buy you a beer or cup of coffee or somethign.

**Comment by withanhdammit** [comment]
That I can do.  My first reaction is "389 entities?  Holy hell that's insane!"

**Comment by travisghansen** [comment]
Or a bunch of firewall and/or nat rules..

**Comment by travisghansen** [comment]
How's the integration been so far? Any gaps that need to be filled in?

The device_tracker stuff is being updated to have much better configuration options etc and a few services will be added but otherwise I think it's relatively complete.

**Comment by withanhdammit** [comment]
No gaps so far, I'm definitely liking being able to chart stuff. I have been working on other config stuff, not as much as on the pfSense.  Frigate is a freaking cool NVR, and I've been tweaking that a bunch.

On the charts note, I did find out how to edit the labels so packets/s is abbreviated to pkt/s.  Turns out to be pretty easy!
```
type: custom:apexcharts-card
series:
  - entity: sensor.packets
    unit: pkt/s
```
