### ISSUE TITLE
CPU Frequency Current often 0

### ISSUE THREAD

**Issue by nagyrobi** [travisghansen/hass-pfsense#31]
The values reported for the "CPU Frequency Current" sensor should be filtered against 0 values:

![kép](https://user-images.githubusercontent.com/1550668/141647576-f255c83d-45d9-4842-86b4-39c4759286e3.png)

**Comment by travisghansen** [comment]
Interesting, I don't see that behavior on my machine. I'm not really sure what I'd change either as I don't know what is considered the current frequency (ie: using the last frequency doesn't seem like a great idea either).

What cpu do you have and does the value as shown in the pfSense UI ever show 0?

**Comment by nagyrobi** [comment]
![kép](https://user-images.githubusercontent.com/1550668/141651534-8615be8b-9f87-4ea2-9824-851a8cfb1df4.png)
Never seen it as 0.
I think you should simply add an if, when value returned is 0, don't updated the sensor value, that's all.

**Comment by travisghansen** [comment]
That's just it, I *must* return something based on how this integration works. The only relatively sane option here is to keep track of the previous value (that was above 0) and send that.

**Comment by nagyrobi** [comment]
That would be good.

**Comment by travisghansen** [comment]
Can you try out the `next` branch? Let me know how it goes.

**Comment by nagyrobi** [comment]
No such branch in the repo on github.

**Comment by nagyrobi** [comment]
Seems better now. The only glitch happens right after HA restart, as it may start with 0, and stays like that until first move from there.

Wonder how important is this anyway? Could be disabled by default... And one could only enable it if really wants it, and provides consistent data...

**Comment by travisghansen** [comment]
I think it's a value that people are generally interested in which is why it's enabled by default. You're welcome to disable it if you don't care about the entity (it has no impact on performance as all the data is batched together in a single call every poll interval).

I'm not sure why you're seeing a value of `0` but I wouldn't be too concerned about it.

**Comment by travisghansen** [comment]
I've just changed the code to send unknown state if the value is 0 (and a previous non-0 value is unavailable).
