### ISSUE TITLE
pfsense is running in a VM, integration shows 32F for temperature?

### ISSUE THREAD

**Issue by wkearney99** [travisghansen/hass-pfsense#38]
I'm only beginning to look into the various things this plug-in provides, and I have a past history of doing software QA.  I tend to "find things".  Don't shoot the messenger!

My pfsense install is on a VM.  As such it doesn't have access to all the same things a bare-metal install might.  One of which seems to be whatever value pfsense uses for "Temp".  When I look at the pfsense main page for the router it does not show a temp variable.  It's selected in the (wrench) submenu for the box, but no entry shows up for it in-between MBUF and Load Average.  I gather this is because pfsense is being smart about not showing what it can't provide?

I still have the overview configured as a default dynamic one, so I don't miss anything new being added.  I'll get to configuring my own cards at a later point.  

When I look at the dashboard "Sensor" card the "router System Temperature" is showing as 32F.  The sensor.router_system_temperature entity is enabled.  I'm guessing the XMLRPC is returning something being interpreted as zero, and converted to Fahrenheit 32F?

I suppose I should look into whether it's possible for the VM to be configured to pass this info.  I'll ignore the temp entity until then.

**Comment by travisghansen** [comment]
Yeah I’m aware of that issue actually and will just change it to return unknown instead of 0. In either case just disable the entity since it won’t work for you anyway and you won’t see it anymore.

**Comment by wkearney99** [comment]
Does the XMLRPC give you just a zero?  While I can't imagine any situations where you'd actually have a 0 temp value, it'd be best to know if it's actually a non-existent value versus a bogus one.   It might be an issue to raise over on the pfsense site.

I had planned already to disable the entity.  But as time goes on, using HA to monitor various things, temperature for devices is handy to track and handle if/when it goes out of bounds.  

I'll do some digging to find out if I can get the data passed into the VM, and meanwhile close this issue.

**Comment by travisghansen** [comment]
The data returned by pfsense actually is a 0 which is unfortunate. I’ll reopen until I’ve updated code to return unknown.

**Comment by travisghansen** [comment]
Fixed and tagged in `v0.2.0`.
