### ISSUE TITLE
Gateway status remains down

### ISSUE THREAD

**Issue by nagyrobi** [travisghansen/hass-pfsense#40]
I had an internet service outage which was fixed by power-cycling the CPE. In HA the gateway went down, but after restoring the internet access, the sensor state didn't recover in HA. Also loss stays at 100%.
In pfSense dashboard everything is OK...

**Comment by nagyrobi** [comment]
Only restarting HA fixes it..

**Comment by travisghansen** [comment]
That sounds pretty odd. We probably need to put some debug logging in to observe the response data from the api calls and see what is being returned.

**Comment by travisghansen** [comment]
Was *anything* updating? Meaning any of the pfsense sensors..

**Comment by nagyrobi** [comment]
Yes. CPU usage for example was updading well.
