### ISSUE TITLE
request: Add CPU usage percent

### ISSUE THREAD

**Issue by ghvader** [travisghansen/hass-pfsense#41]
this integration has memory usage % but not CPU usage %
please add
thanks!

**Comment by travisghansen** [comment]
It’s actually already in main, I just have snapped a release with it yet.

**Comment by travisghansen** [comment]
https://github.com/travisghansen/hass-pfsense/commit/556438e192aed0e09730b2aaade277b1f5238844

**Comment by ghvader** [comment]
great thanks!!
