### ISSUE TITLE
Please...

### ISSUE THREAD

**Issue by SirGoodenough** [travisghansen/hass-pfsense#44]
Sorry, not really an issue, but Please add a pay link or buy me a coffee or something.
This is fantastic and I've been looking for something like it for years.  My nmap only gave me 3 entities.

Add something to your readme so I can say THANK YOU properly...

Also I want to do a video about this on my YT page and want to suggest that folks also drop you some thank-you's.

**Comment by travisghansen** [comment]
Welcome! Thank you for the kind words and offer of support! For now I’ll politely decline but I’d love to watch the video after it’s produced and ready :)

I am always interested in what people find most useful. I’d love to know which features you’re using and if there are others that may be of interest that are missing.

**Comment by iamk3** [comment]
> Sorry, not really an issue, but Please add a pay link or buy me a coffee or something. This is fantastic and I've been looking for something like it for years. My nmap only gave me 3 entities.
> 
> Add something to your readme so I can say THANK YOU properly...
> 
> Also I want to do a video about this on my YT page and want to suggest that folks also drop you some thank-you's.

I'd love to see the YT video as well! I'm looking to implement this too!
