### ISSUE TITLE
PfSense not listed in integrations

### ISSUE THREAD

**Issue by kaliblazin707** [travisghansen/hass-pfsense#47]
Hello!
I have added the repo to HACS, however I am not seeing the integration in Config > Integrations. Am I missing something?

**Comment by travisghansen** [comment]
Welcome! The repo is now included in the default hacs repos actually so it shouldn’t be necessary to add the repo manually.

Regardless, after restarting hass make sure to do a hard refresh in the browser ui.

Let me know how it goes!

**Comment by kaliblazin707** [comment]
![2](https://user-images.githubusercontent.com/20490866/143664043-506884b9-7e35-4bee-af2b-e480ba80f7d6.PNG)
![1](https://user-images.githubusercontent.com/20490866/143664047-5b7940ef-81fe-4b66-9e0f-d27d91148e94.PNG)
I have HA running in TrueNAS Scale, thats running as a VM on my home server. (It has 24 of its own xeon cores and 32gigs of ram, I have plenty of juice to run TrueNAS as a VM)
I am new to HACS, and HA in general really, but I managed to get the TP-Link Omada integration working through HACS. 

  You're right, I did not need to manually add the Repo, and I restarted the HA server, Then stopped n started the app in TrueNAS. Then restarted TrueNAS from proxmox. 
  
  Still cant find it in Config > Integrations. :/ I feel like I am missing something simple lmao.

**Comment by travisghansen** [comment]
Can you login with an incognito window and see if it shows up?

**Comment by kaliblazin707** [comment]
It does! TF?! Lol
TY TY. Weird, Chrome caching issue?

**Comment by travisghansen** [comment]
That’s what I meant by doing a hard refresh in the browser ui (ctrl shift r in chrome for example).

**Comment by kaliblazin707** [comment]
Oh, I thought you meant HA, I apologize. Thank you again so much!
