### ISSUE TITLE
missing function openvpn_get_active_servers

### ISSUE THREAD

**Issue by orcema** [travisghansen/hass-pfsense#53]
On latest update TAG 3.1 i get an error on the pfsense related to missing function openvpn_get_active_servers

```
Crash report begins.  Anonymous machine information:

amd64
12.2-STABLE
FreeBSD 12.2-STABLE 1b709158e581(RELENG_2_5_0) pfSense

Crash report details:

PHP Errors:
[25-Dec-2021 10:40:02 Europe/Luxembourg] PHP Fatal error:  Uncaught Error: Call to undefined function openvpn_get_active_servers() in /usr/local/www/xmlrpc.php(145) : eval()'d code:54
Stack trace:
#0 /usr/local/www/xmlrpc.php(145): eval()
#1 /usr/local/share/pear/XML/RPC2/Server/CallHandler/Instance.php(141): pfsense_xmlrpc_server->exec_php('\nini_set('displ...')
#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Server_Callhandler_Instance->__call('pfsense.exec_ph...', Array)
#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server->getResponse()
#4 /usr/local/www/xmlrpc.php(883): XML_RPC2_Backend_Php_Server->handleCall()
#5 {main}
  thrown in /usr/local/www/xmlrpc.php(145) : eval()'d code on line 54



No FreeBSD crash data found.
```

**Comment by travisghansen** [comment]
That code is only in main…what tag are you running?

**Comment by ozrouter** [comment]
same bug here... 3.1 and 4

the 4 upgrade on latest HA connects, then errors (with the ssl check disabled):

`Retrying setup: <ProtocolError for admin:pass@pfsense.localdomain:8282/xmlrpc.php: 500 Internal Server Error>`

**Comment by travisghansen** [comment]
What version of pfsense are you both using?

**Comment by ozrouter** [comment]
he looks to be on 2_5_0
I'm on 2_5_1 (worked previously)

**Comment by travisghansen** [comment]
I’m wondering if something has changed slightly between versions. It’s easy enough to fix but I’m interested in knowing why it’s not working on older point releases.

**Comment by travisghansen** [comment]
Try updating to the most recent `main` with commit https://github.com/travisghansen/hass-pfsense/commit/ad279f34d6ebf0d24e94bdfe21d3521bf698f91d and see how it goes.

**Comment by orcema** [comment]
In the mean time i upgraded my pfsense to 2_5_1 and the latest version TAG V0.4.0 works for me

**Comment by travisghansen** [comment]
Is there a particular reason you don’t run the latest (2.5.2)?

**Comment by ozrouter** [comment]
oh! I had updates turned off, oops.

**Comment by travisghansen** [comment]
Good reason to use the new update sensor I added! :)

**Comment by ozrouter** [comment]
yes! Done.

**Comment by orcema** [comment]
> Is there a particular reason you don’t run the latest (2.5.2)?

Sorry i ment i updated to 2_5_2 and my issues were on the 2_5_ 1  :confused:

**Comment by austinbeam** [comment]
I'm seeing the same issue with PfSense 2.5.1 and v0.4.0. I'm sure ad279f3 will fix it, but am using HACS so just lazily reverted to v0.3.1 until this commit makes it to a tagged release. I have been hesitant to upgrade PfSense because last upgrade I went through a lot of pain and am currently remote. Will do it eventually 😄 

Thanks for all the great work, I am really enjoying this integration.

**Comment by travisghansen** [comment]
That's fair. I just tagged `v0.4.1`. Give it a go and let me know if it clears things up.

**Comment by austinbeam** [comment]
Thanks @travisghansen. Issue went away after upgrading pfsense. Sorry I never followed up. Have a good one.
