### ISSUE TITLE
Option Device Tracker Consider Home not there 

### ISSUE THREAD

**Issue by wauswaus** [travisghansen/hass-pfsense#54]
Installed everything as described however I'm missing the "Device Tracker Consider Home" setting when setting up the integration. Where can I configure this?

I'm looking into using this for tracking phones around the house and I would like to tweak this value as I see some false negatives.
Thanks for the work!

**Comment by travisghansen** [comment]
It’s not in release yet only main, but I’ll snap a new release now..

**Comment by travisghansen** [comment]
Tagged `v0.4.0` which should include the feature.

**Comment by wauswaus** [comment]
See it! Great job, thanks
