### ISSUE TITLE
Login SSL Issue

### ISSUE THREAD

**Issue by Bounties1337** [travisghansen/hass-pfsense#59]
Hi Folks,

Perhaps a bit of dumb question. But Yeah, eventually you can help.

I am already stuck on the initial setup of PfSense integration, choosing SSL and w/o SSL connect.
When running w/ SSL I do receive prompt "SSL Failure", so I changed to
When running w/o SSL I do receive "%key:common::config_flow::error::invalid_auth%"

The format of URL is actually straight forward <scheme>://(ip):(port)
Scheme running over https.

Reading network trace, Wireshark, I see Homeassistant exchanging the certificate but reporting "Alert" Unknown CA.

I assume I am not the only user discovering that obstacle. But Yeah, as said, I hope reported issue is not to dumb... .

Thanks for the help.

**Comment by travisghansen** [comment]
Have you tried unchecking `Verify SSL certificate`?

**Comment by Bounties1337** [comment]
> Have you tried unchecking `Verify SSL certificate`?

Yes, I have. Pls. see: When running w/o SSL I do receive "%key:common::config_flow::error::invalid_auth%"

**Comment by travisghansen** [comment]
Running without ssl means (to me) you put in http instead of https…not necessarily that you disabled verify ssl.

In any case, can you send the hass logs when the failure(s) happen?

**Comment by Bounties1337** [comment]
My Bad! I meant SSL Check off.

Homeassistant Log:
2022-01-09 22:07:00 ERROR (MainThread) [custom_components.pfsense.config_flow] Unexpected err=ConnectionRefusedError(111, 'Connection refused'), type(err)=<class 'ConnectionRefusedError'>

Wireshark Log:
Homeassistant sent to PfSense: "TLSv1.3 Record Layer: Alert (Level: Fatal, Description: Unknown CA)"
After that I can see FIN ACK sent by PfSense consequently RST(Reset).

Is there something that I may have overlooked on PfSense to accept.

Thanks!

**Comment by travisghansen** [comment]
Seems to me that pfsense is just killing the connection. Are you putting the same url you use to access the pfsense gui from? Is the machine running hass able to curl the pfsense login page for example?

**Comment by Bounties1337** [comment]
> Seems to me that pfsense is just killing the connection. Are you putting the same url you use to access the pfsense gui from? Is the machine running hass able to curl the pfsense login page for example?

Yes indeed. It is the same URL, I run the administration over https://.... . 
I did a normal connect test from HA CLI with ssh to PfSense which works like a charm.

While curl failed with the following error prompt:
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by travisghansen** [comment]
Add -k to the curl command and send the output if you don’t mind (please cleanse anything sensitive, and also note creds shouldn’t be required just to access the login page).

**Comment by Bounties1337** [comment]
> Add -k to the curl command and send the output if you don’t mind (please cleanse anything sensitive, and also note creds shouldn’t be required just to access the login page).

Sure thing!  Enclosed:

root@host:~# curl -k --user homeassistant:pass https://ip
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css" type="text/css">
	    <link rel="stylesheet" href="/css/login.css?v=1622201721" type="text/css">
		<title>pfSense - Login</title>
		<script type="text/javascript">
			//<![CDATA{
			var events = events || [];
			//]]>
		</script>
	<script type="text/javascript">if (top != self) {top.location.href = self.location.href;}</script><script type="text/javascript">var csrfMagicToken = "sid:5b8fdad9787d5cfda087edf5920cd1b197f67755,1641856688;ip:df801632284284207faf98118684d51069e99444,1641856688";var csrfMagicName = "__csrf_magic";</script><script src="/csrf/csrf-magic.js" type="text/javascript"></script></head>

	<body id="login" >
		<div id="total">
			<header>
				<div id="headerrow">
					<div class="row">
						
						<div class="col-sm-4">
							<div id="logodiv" style="text-align:center" class="nowarning">
								<svg id="logo" role="img" aria-labelledby="pfsense-logo" x="0px" y="0px" viewBox="0 0 282.8 84.2">
	<title id="pfsense-logo-svg">pfSense Logo</title>
	<path class="logo-st0" d="M27.8,57.7c2.9,0,5.4-0.9,7.5-2.6c2.1-1.7,3.6-4,4.4-6.8c0.8-2.8,0.6-5.1-0.5-6.8c-1.1-1.7-3.2-2.6-6.1-2.6 c-2.9,0-5.4,0.9-7.5,2.6c-2.1,1.7-3.5,4-4.3,6.8c-0.8,2.8-0.7,5.1,0.5,6.8C22.8,56.9,24.8,57.7,27.8,57.7"/>
	<path class="logo-st0" d="M115.1,46.6c-1.5-0.8-3-1.4-4.7-1.8c-1.7-0.4-3.2-0.7-4.7-1.1c-1.5-0.3-2.7-0.7-3.6-1.1c-0.9-0.4-1.4-1.1-1.4-2 c0-1.1,0.5-1.9,1.4-2.4c0.9-0.5,1.9-0.7,2.8-0.7c2.8,0,5,1,6.7,3.1l7-7c-1.7-1.8-3.9-3.1-6.4-3.8c-2.5-0.7-5-1.1-7.4-1.1 c-1.9,0-3.9,0.2-5.7,0.7c-1.9,0.5-3.6,1.2-5,2.3c-1.5,1-2.6,2.3-3.5,3.9c-0.9,1.6-1.3,3.5-1.3,5.7c0,2.3,0.5,4.2,1.4,5.6 c0.9,1.4,2.1,2.5,3.6,3.3c1.5,0.8,3,1.3,4.7,1.7c1.7,0.4,3.2,0.7,4.7,1.1c1.5,0.3,2.7,0.7,3.6,1.2c0.9,0.5,1.4,1.2,1.4,2.2 c0,1-0.5,1.7-1.6,2.1c-1.1,0.4-2.3,0.6-3.6,0.6c-1.7,0-3.3-0.3-4.6-1c-1.3-0.7-2.5-1.7-3.6-3l-7,7.7c1.8,1.9,4.1,3.2,6.7,3.9 c2.7,0.7,5.3,1.1,7.9,1.1c2,0,4-0.2,6.1-0.6c2-0.4,3.9-1,5.5-2c1.6-0.9,3-2.2,4-3.8c1-1.6,1.6-3.5,1.6-5.9c0-2.3-0.5-4.2-1.4-5.6 C117.7,48.6,116.5,47.4,115.1,46.6"/>
	<path class="logo-st0" d="M156.3,34.1c-1.5-1.7-3.3-3-5.5-3.9c-2.2-0.9-4.6-1.4-7.2-1.4c-2.9,0-5.6,0.5-8.1,1.4c-2.5,0.9-4.7,2.2-6.6,3.9 c-1.9,1.7-3.3,3.8-4.4,6.2c-1.1,2.4-1.6,5.1-1.6,8c0,3,0.5,5.6,1.6,8c1.1,2.4,2.5,4.5,4.4,6.2c1.9,1.7,4.1,3,6.6,3.9 c2.5,0.9,5.2,1.4,8.1,1.4c3,0,5.9-0.6,8.7-1.9c2.8-1.3,5.1-3.1,7-5.4l-8-5.9c-1,1.3-2.1,2.4-3.4,3.3c-1.3,0.8-2.9,1.3-4.8,1.3 c-2.2,0-4.1-0.7-5.7-2c-1.5-1.3-2.5-3.1-3-5.2H161v-3.6c0-3-0.4-5.6-1.2-8C159,37.9,157.8,35.8,156.3,34.1 M134.3,44.1 c0.1-0.9,0.3-1.8,0.7-2.6c0.4-0.8,0.9-1.6,1.6-2.2c0.7-0.6,1.5-1.2,2.5-1.6c1-0.4,2.1-0.6,3.4-0.6c2.1,0,3.8,0.7,5.1,2.1 c1.3,1.4,2,3,1.9,5H134.3z"/>
	<path class="logo-st0" d="M198.3,33.8c-1-1.6-2.4-2.8-4.2-3.7c-1.8-0.9-4.1-1.3-7-1.3c-1.4,0-2.7,0.2-3.8,0.5c-1.2,0.4-2.2,0.8-3.1,1.4 c-0.9,0.6-1.7,1.2-2.4,1.9c-0.7,0.7-1.2,1.4-1.5,2.1H176v-5.1h-11v37.2h11.5V48.4c0-1.2,0.1-2.4,0.2-3.5c0.2-1.1,0.5-2.1,1-3 c0.5-0.9,1.2-1.6,2.1-2.1c0.9-0.5,2.1-0.8,3.6-0.8c1.5,0,2.6,0.3,3.4,0.9c0.8,0.6,1.4,1.4,1.8,2.4c0.4,1,0.6,2,0.7,3.2 c0.1,1.1,0.1,2.3,0.1,3.3v18.2h11.5V46.4c0-2.5-0.2-4.8-0.5-7C199.9,37.3,199.3,35.4,198.3,33.8"/>
	<path class="logo-st0" d="M231.5,46.6c-1.5-0.8-3-1.4-4.7-1.8c-1.7-0.4-3.2-0.7-4.7-1.1c-1.5-0.3-2.7-0.7-3.6-1.1c-0.9-0.4-1.4-1.1-1.4-2 c0-1.1,0.5-1.9,1.4-2.4c0.9-0.5,1.9-0.7,2.8-0.7c2.8,0,5,1,6.7,3.1l7-7c-1.7-1.8-3.9-3.1-6.4-3.8c-2.5-0.7-5-1.1-7.4-1.1 c-1.9,0-3.9,0.2-5.7,0.7c-1.9,0.5-3.6,1.2-5,2.3c-1.5,1-2.6,2.3-3.5,3.9c-0.9,1.6-1.3,3.5-1.3,5.7c0,2.3,0.5,4.2,1.4,5.6 c0.9,1.4,2.1,2.5,3.6,3.3c1.5,0.8,3,1.3,4.7,1.7c1.7,0.4,3.2,0.7,4.7,1.1c1.5,0.3,2.7,0.7,3.6,1.2c0.9,0.5,1.4,1.2,1.4,2.2 c0,1-0.5,1.7-1.6,2.1c-1.1,0.4-2.3,0.6-3.6,0.6c-1.7,0-3.3-0.3-4.6-1c-1.3-0.7-2.5-1.7-3.6-3l-7,7.7c1.8,1.9,4.1,3.2,6.7,3.9 c2.7,0.7,5.3,1.1,7.9,1.1c2,0,4-0.2,6.1-0.6c2-0.4,3.9-1,5.5-2c1.6-0.9,3-2.2,4-3.8c1-1.6,1.6-3.5,1.6-5.9c0-2.3-0.5-4.2-1.4-5.6 C234.1,48.6,232.9,47.4,231.5,46.6"/>
	<path class="logo-st0" d="M277.4,51.9v-4.2c-0.1-2.7-0.5-5.2-1.2-7.4c-0.8-2.4-2-4.5-3.5-6.2c-1.5-1.7-3.3-3-5.5-3.9 c-2.2-0.9-4.6-1.4-7.2-1.4c-2.9,0-5.6,0.5-8.1,1.4c-2.5,0.9-4.7,2.2-6.6,3.9c-1.9,1.7-3.3,3.8-4.4,6.2c-1.1,2.4-1.6,5.1-1.6,8 c0,3,0.5,5.6,1.6,8c1.1,2.4,2.5,4.5,4.4,6.2c1.9,1.7,4.1,3,6.6,3.9c2.5,0.9,5.2,1.4,8.1,1.4c3,0,5.9-0.6,8.7-1.9 c2.8-1.3,5.1-3.1,7-5.4l-8-5.9c-1,1.3-2.1,2.4-3.4,3.3c-1.3,0.8-2.9,1.3-4.8,1.3c-2.2,0-4.1-0.7-5.7-2c-1.5-1.3-2.5-3.1-3-5.2H277.4 z M250.7,44.1c0.1-0.9,0.3-1.8,0.7-2.6c0.4-0.8,0.9-1.6,1.6-2.2c0.7-0.6,1.5-1.2,2.5-1.6c1-0.4,2.1-0.6,3.4-0.6 c2.1,0,3.8,0.7,5.1,2.1c1.3,1.4,2,3,1.9,5H250.7z"/>
	<path class="logo-st1" d="M52.6,38.9l2.6-9.2h4.6l1.8-6.6c0.6-2,1.3-4,2.2-5.8c0.8-1.8,2-3.4,3.4-4.8c1.4-1.4,3.2-2.5,5.3-3.3 c2.1-0.8,4.8-1.2,7.9-1.2c0.8,0,1.5,0,2.3,0.1c-0.7-2.9-3.3-5-6.3-5.1H11.9c-3.6,0-6.5,3-6.5,6.6V67l10.5-37.3h10.6l-1.4,4.9h0.2 c0.6-0.7,1.4-1.3,2.4-2c1-0.7,2-1.3,3.1-1.9c1.1-0.6,2.3-1,3.6-1.4c1.3-0.4,2.6-0.5,3.9-0.5c2.8,0,5.1,0.5,7.1,1.4 c2,0.9,3.5,2.3,4.7,4c1,1.5,1.6,3.3,1.9,5.4l0.8-0.6H52.6z"/>
	<path class="logo-st2" d="M82.1,17.9c-0.5-0.1-1.1-0.2-1.8-0.2c-1.8,0-3.3,0.4-4.5,1.2c-1.1,0.8-2.1,2.4-2.8,4.9l-1.7,5.9h6.5l1.6,5.1 l-4.2,4.1h-6.5l-7.9,28H49.4l7.9-28h-4.4L52,39.5c0,0.2,0.1,0.5,0.1,0.7c0.2,2.3-0.1,4.9-0.9,7.7c-0.7,2.6-1.8,5.1-3.3,7.5 c-1.5,2.4-3.2,4.5-5.1,6.3c-2,1.8-4.2,3.3-6.6,4.4c-2.4,1.1-4.9,1.6-7.6,1.6c-2.4,0-4.5-0.4-6.4-1.1c-1.9-0.7-3.2-2-4-3.8h-0.2 l-5,17.7h63.3c3.6,0,6.6-2.9,6.6-6.6V18.2C82.6,18.1,82.3,18,82.1,17.9"/>
	<path class="logo-st0" d="M277.6,68.5h0.8c0.4,0,0.6-0.1,0.7-0.2c0.1-0.1,0.2-0.2,0.2-0.4c0-0.1,0-0.2-0.1-0.3c-0.1-0.1-0.1-0.2-0.3-0.2 c-0.1,0-0.3-0.1-0.6-0.1h-0.7V68.5z M277,70.6v-3.8h1.3c0.5,0,0.8,0,1,0.1c0.2,0.1,0.4,0.2,0.5,0.4c0.1,0.2,0.2,0.4,0.2,0.6 c0,0.3-0.1,0.5-0.3,0.7c-0.2,0.2-0.5,0.3-0.8,0.3c0.1,0.1,0.2,0.1,0.3,0.2c0.2,0.2,0.3,0.4,0.6,0.8l0.5,0.7h-0.8l-0.3-0.6 c-0.3-0.5-0.5-0.8-0.6-0.9c-0.1-0.1-0.3-0.1-0.5-0.1h-0.4v1.6H277z M278.6,65.7c-0.5,0-1,0.1-1.5,0.4c-0.5,0.3-0.8,0.6-1.1,1.1 c-0.3,0.5-0.4,1-0.4,1.5c0,0.5,0.1,1,0.4,1.5c0.3,0.5,0.6,0.8,1.1,1.1c0.5,0.3,1,0.4,1.5,0.4c0.5,0,1-0.1,1.5-0.4 c0.5-0.3,0.8-0.6,1.1-1.1c0.3-0.5,0.4-1,0.4-1.5c0-0.5-0.1-1-0.4-1.5c-0.3-0.5-0.6-0.8-1.1-1.1C279.6,65.8,279.1,65.7,278.6,65.7z M278.6,65.1c0.6,0,1.2,0.2,1.8,0.5c0.6,0.3,1,0.7,1.3,1.3c0.3,0.6,0.5,1.2,0.5,1.8c0,0.6-0.2,1.2-0.5,1.8c-0.3,0.6-0.8,1-1.3,1.3 c-0.6,0.3-1.2,0.5-1.8,0.5c-0.6,0-1.2-0.2-1.8-0.5c-0.6-0.3-1-0.8-1.3-1.3c-0.3-0.6-0.5-1.2-0.5-1.8c0-0.6,0.2-1.2,0.5-1.8 c0.3-0.6,0.8-1,1.3-1.3C277.4,65.2,278,65.1,278.6,65.1z"/>
</svg>
							</div>
						</div>

						
						<div class="col-sm-4 nowarning msgbox text-center text-danger">
						</div>

						
						<div class="col-sm-4 nowarning msgbox text-center">
							<span id="hostspan">
								<a><h4>Login to pfSense</h4></a>
							</span>
						</div>
					</div>
	            </div>
	        </header>

	        <div style="background: #000000;" class="pagebody">
	        	<div class="col-sm-4"></div>

	        	<div class="col-sm-4 offset-md-4 logoCol">
					<div class="loginCont center-block">
		                <form method="post"  class="login"><input type='hidden' name='__csrf_magic' value="sid:5b8fdad9787d5cfda087edf5920cd1b197f67755,1641856688;ip:df801632284284207faf98118684d51069e99444,1641856688" />
			                <p class="form-title">Sign In</p>
			                <input name="usernamefld" id="usernamefld" type="text" placeholder="Username" autocorrect="off" autocapitalize="none"/>
			                <input name="passwordfld" id="passwordfld" type="password" placeholder="Password" />
			                <input type="submit" name="login" value="Sign In" class="btn btn-success btn-sm" />
		                </form>
					</div>
	            </div>

	        	<div class="col-sm-4"></div>
	        </div>

	        <footer id="3">
	            <div id="footertext">
					<p class="text-muted">
						<a target="_blank" href="https://pfsense.org">pfSense</a> is developed and maintained by <a target="_blank" href="https://netgate.com">Netgate. </a> &copy; ESF 2004 - 2022<a target="_blank" href="https://pfsense.org/license"> View license.</a>					</p>
	            </div>
	        </footer>
	    </div>

		<script type="text/javascript">
		//<![CDATA[
			/* Prevent duplicate submission  */
			events.push(function() {
				var submitted = false;

				$(form).submit(function(e){
					if (submitted) {
						e.preventDefault();
					} else {
						submitted = true;
						// Form is submitted because default action is not prevented
					}
				});
			});
		//]]>
		</script>

	    <script src="/vendor/jquery/jquery-3.5.1.min.js?v=1622201721"></script>
		<script src="/vendor/bootstrap/js/bootstrap.min.js?v=1622201721"></script>
		<script src="/js/pfSense.js?v=1622201721"></script>

		<script type="text/javascript">
		//!<[CDATA[
		events.push(function() {
			document.cookie=
				"cookie_test=1" +
				"; secure";

			if (document.cookie.indexOf("cookie_test") == -1) {
				alert("The browser must support cookies to login.");
			}

			// Delete it
			document.cookie = "cookie_test=1; expires=Thu, 01-Jan-1970 00:00:01 GMT";
		});
		//]]>
		</script>

	<script type="text/javascript">CsrfMagic.end();</script></body>
</html>

**Comment by andres-leon** [comment]
Hello,
i'm encountering a similar issue. in the pfsense logs i see the following message:

`/xmlrpc.php: webConfigurator authentication error for 'ha' from 192.168.1.114` 

The user 'ha' has admin rights and I also explicitly gave it:
`WebCfg - XMLRPC Interface Stats
WebCfg - XMLRPC Library
System - HA node sync`

I'm running pfsense 2.4.4-RELEASE-p3.

any help would be much appreciated!

**Comment by travisghansen** [comment]
Does something make you believe the error is ssl related then? Seems not to be if you’re getting that error..

**Comment by andres-leon** [comment]
> Does something make you believe the error is ssl related then? Seems not to be if you’re getting that error..

You're right. I don't think it's SSL related. Posted in the wrong issue. i'll keep searching to see if i can find the right one.

**Comment by mbrennan** [comment]
I had this issue when I first tried to install and configure this integration today.  I found a pfSense rule that blocks the connection from Home Assistant to pfSense.  I added a specific rule above the one that blocks it and this error went away.  Perhaps a more helpful error message would be better for others, such as "Unable to connect to pfSense.  Make sure you don't have a firewall rule blocking access to it," or something along those lines.

**Comment by NorthernMunkey** [comment]
ditto getting the same error, via https get ssl error, via http either by name or ip, get Incorrect URL (redirect) ( which i assume it's due to me forcing https from pfsense. I too am using lets encrypt, ( via acme)  If i re apply a self signed cert in pfsense,  same error, it's only when i tell pfsense to use http and not https then it works

**Comment by travisghansen** [comment]
I'm not sure what I can do here :( I can't think of any reason why the xmlrpc client would have errors if the cert is valid.

Does anyone else have any other info they can share? I'm doing a little work on this project this week and will look into it if there's some actionable info I can use to reproduce etc. Or if someone wants to setup a test env and get me access somehow I can do some debugging remotely.

**Comment by damaar666** [comment]
Mine is now working but I can't help with why.  Short story is my server had a crash (lost the OS running on a USB stick - Unraid) and had to reset a few things up.  Ended up having to reconfigure the docker container (appdata folder intact) and pfsense integration started working.  No other changes that I can think of.  I'll try to have a poke around and see if anything else changed.

**Comment by selfownership** [comment]
> I am also seeing this error. What I have to add:
> 
> * I have a user 'hass' with the` System - HA node sync`
> * Also tried with 'admin' user
> * Tried both verifying SSL and not
> 
I'm also getting the "User has insufficient privileges (System - HA node sync)" error to integrate in Home Assistant.  Are there instructions on what specific step to configure pfSense to integrate this?

**Comment by travisghansen** [comment]
Anything still needed on this?

**Comment by damaar666** [comment]
Still all good from my perspective. Never did find a logical reason why it started working, sorry I wasn't much help.  Integration is great, thank-you for all your work @travisghansen
