### ISSUE TITLE
Feature Request: Ability to change DHCP assigned DNS servers

### ISSUE THREAD

**Issue by Iceman248** [travisghansen/hass-pfsense#73]
At times, this would be very useful if I could change the DNS server for DHCP clients based on when my regular DNS server is down which I like to use exclusively in certain cases. Could this be added? Thanks.

**Comment by travisghansen** [comment]
Welcome! Seems doable but my time for working on this project is limited atm so not sure when I can get to it.

**Comment by travisghansen** [comment]
Doing some maintenance on this project this week. I will likely implement this as a pretty 'raw' service that let's you do pretty much whatever you want with pfSense by writing snippets of php code to meet your needs. I've drafted up a simple example here:

```
require_once '/etc/inc/config.inc';
global $config;
$interface = "lan";
if (!is_array($config["dhcpd"])) {
  $config["dhcpd"] = [];
}
if (!is_array($config["dhcpd"][$interface])) {
  $config["dhcpd"][$interface] = [];
}
$config["dhcpd"][$interface]["dnsserver"] = "127.0.0.1";
write_config("HASS - exec_php: stuff and stuff");
// reload services, etc here as necessary
$toreturn = [
  "data" => true,
];
```

**Comment by travisghansen** [comment]
`exec_php` service released with `v0.5.0` https://github.com/travisghansen/hass-pfsense/commit/c557539b2cbce63d91df805bd7e12cdbc47afa23

see `EXEC_EXAMPLES.md` for some ideas on how to achieve this.

**Comment by Iceman248** [comment]
Thanks for putting this in. I'm getting around to trying to set this up, but I cannot understand what parts of that code I would change I would change to achieve what I want. I know I would insert DNS, interface name, etc, but not sure all of where it goes.

**Comment by travisghansen** [comment]
Use it when invoking the service: https://github.com/travisghansen/hass-pfsense/blob/main/README.md?plain=1#L187-L212

**Comment by Iceman248** [comment]
So with the following, if I wanted to change the DHCP assigned DNS server on the "lan" interface to "192.168.0.1", I just use as is. Otherwise, I modify just "lan" and/or "192.168.0.1"? If I wanted to change secondary DNS, is there a bit of code to add to this to accomplish that? Thanks.

`require_once '/etc/inc/config.inc';
global $config;
$interface = "lan";
$dns = "192.168.0.1";

if (!is_array($config["dhcpd"])) {
    $config["dhcpd"] = [];
}
if (!is_array($config["dhcpd"][$interface])) {
    $config["dhcpd"][$interface] = [];
}

$config["dhcpd"][$interface]["dnsserver"] = $dns;

write_config("HASS - exec_php: update dhcpd dns server");

// reload services, etc here as necessary
$toreturn = [
    "data" => true,
];`

**Comment by travisghansen** [comment]
It looks like this would work..

```
// empty the current values
$config["dhcpd"][$interface]["dnsserver"] = [];
// add new values to the list
$config["dhcpd"][$interface]["dnsserver"][] = $dnsfoo;
$config["dhcpd"][$interface]["dnsserver"][] = $dnsbar;
...
```

For reference this is what the config block looks like (in php land) with 1 or 2 respectively:

```
      ["dnsserver"]=>
      array(1) {
        [0]=>
        string(7) "1.1.1.1"
      }

      ["dnsserver"]=>
      array(2) {
        [0]=>
        string(7) "1.1.1.1"
        [1]=>
        string(7) "8.8.8.8"
      }
```

**Comment by Iceman248** [comment]
Thanks again. It worked, so I must have modified it correctly. This is what it looked like.

```
  require_once '/etc/inc/config.inc';
  global $config;
  $interface = "lan";
  $dnsfoo = "192.168.0.1";
  $dnsbar = "192.168.0.1";
  if (!is_array($config["dhcpd"])) {
      $config["dhcpd"] = [];
  }
  if (!is_array($config["dhcpd"][$interface])) {
      $config["dhcpd"][$interface] = [];
  }
  // empty the current values
  $config["dhcpd"][$interface]["dnsserver"] = [];
  // add new values to the list
  $config["dhcpd"][$interface]["dnsserver"][] = $dnsfoo;
  $config["dhcpd"][$interface]["dnsserver"][] = $dnsbar;
  write_config("HASS - exec_php: update dhcpd dns server");
  // reload services, etc here as necessary
  $toreturn = [
      "data" => true,
  ];
```

**Comment by travisghansen** [comment]
Great!

**Comment by Iceman248** [comment]
Can I bother you to tell me what the adjustment is to have this work with OPNsense? Sorry, I knew I was moving there, figured this would be the same, but it's not and I can't figure it out. I changed the file to /conf/config.xml, but still didn't work. Thanks.

**Comment by travisghansen** [comment]
That integration does not have the required services yet. I'm mostly focused on pfsense as that is what I use and simply did opnsense as a byproduct 'for fun'.

**Comment by Iceman248** [comment]
Understood. I actually realized a better way to have the php scripts executed though and it is using the Monit service built-in to OPNsense, so I just need to know the PHP script modifications.
