### ISSUE TITLE
force release/renew interface

### ISSUE THREAD

**Issue by smartekIT** [travisghansen/hass-pfsense#74]
HI,
first thanks for your hard work here guys.

in ssh if we need to force release/renew interface ip specially those WANs configured as DHCP we just do
<pre>service dhclient restart interface_name</pre>

is this something can be done by this script? and if yes how?

Thanks

**Comment by travisghansen** [comment]
Seems feasible but I'm still a bit out before I can dig back into this project again..

**Comment by travisghansen** [comment]
My intent is to make 2 arbitrary services:

- exec arbitrary shell commands/script
- exec arbitrary php code (basically how the whole integration works)

**Comment by travisghansen** [comment]
This can be achieve with the new `exec_command` service in `v0.5.0` from this commit here: https://github.com/travisghansen/hass-pfsense/commit/c557539b2cbce63d91df805bd7e12cdbc47afa23
