### ISSUE TITLE
Feature request: service/switch to change default gateways

### ISSUE THREAD

**Issue by lanrat** [travisghansen/hass-pfsense#76]
First off thanks for making a great pfSense Home Assistant integration!

For my use-case It would be nice if I could have Home Assistant change pfSense's default gateways (IPv4 & IPv6).
I think this could be implemented as either a service call or a switch/toggle.

**Comment by travisghansen** [comment]
new service is available in `v0.5.0` this commit: https://github.com/travisghansen/hass-pfsense/commit/c557539b2cbce63d91df805bd7e12cdbc47afa23
