### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by smsunday86** [travisghansen/hass-pfsense#79]
I've tried setting up the connection between pfSense and Home Assistant, but can't seem to get it to connect. I've set up the connection with https://192.168.1.1, with verify SSL unchecked and I get the following error on pfSense:

PHP ERROR: Type: 1, File: /usr/local/www/xmlrpc.php(141) : eval()'d code, Line: 6, Message: Uncaught Error: Call to undefined function system_get_dhcpleases() in /usr/local/www/xmlrpc.php(141) : eval()'d code:6
Stack trace:
#0 /usr/local/www/xmlrpc.php(141): eval()
#1 /usr/local/share/pear/XML/RPC2/Server/CallHandler/Instance.php(141): pfsense_xmlrpc_server-&gt;exec_php('\nini_set('displ...')
#2 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(135): XML_RPC2_Server_Callhandler_Instance-&gt;__call('pfsense.exec_ph...', Array)
#3 /usr/local/share/pear/XML/RPC2/Backend/Php/Server.php(99): XML_RPC2_Backend_Php_Server-&gt;getResponse()
#4 /usr/local/www/xmlrpc.php(771): XML_RPC2_Backend_Php_Server-&gt;handleCall()
#5 {main}

Here is the log on Home Assistant:
2022-06-04 09:32:15 ERROR (MainThread) [custom_components.pfsense] Unexpected error fetching pfSense pfSense state data: <ProtocolError for user:password@192.168.1.1/xmlrpc.php: 500 Internal Server Error>

**Comment by travisghansen** [comment]
What version if pfsense is this?

**Comment by smsunday86** [comment]
I am currently running 2.4.5-RELEASE-p1 (amd64) on pfSense and core-2022.6.1 on Home Assistant.

**Comment by travisghansen** [comment]
Yeah just update to the latest pfsense and you should be good. Initial development was done against 2.5.2

**Comment by smsunday86** [comment]
That fixed it! thanks for the help!

**Comment by travisghansen** [comment]
A *lot* of sensors are disabled by default, be sure to dig through the disabled sensors to find anything interesting.
