### ISSUE TITLE
Error creating the integration

### ISSUE THREAD

**Issue by UPEngineer** [travisghansen/hass-pfsense#87]
I am trying to install the latest version. This is what I am getting when I click on Submit:

![image](https://user-images.githubusercontent.com/379835/177665705-af30bd89-336b-45f6-a00e-06199352e950.png)

Am I missing something? I am not using SSL.

**Comment by travisghansen** [comment]
The integration was working previously and now does not? Or this is the first time trying to add?

**Comment by travisghansen** [comment]
Also send the hass logs if possible when this error happens.

**Comment by UPEngineer** [comment]
I tired to add the integration for the first time last night.  Same error. Have updated it twice today with the updates you released. Same issue.

How do I get the hass logs?

**Comment by travisghansen** [comment]
Well the error indicates pfsense is redirecting the api request. Can you send a screenshot of the login page working with the address bar?

**Comment by UPEngineer** [comment]
Is this what you are after?

![image](https://user-images.githubusercontent.com/379835/177667081-4974afe1-f1e9-453f-93e1-d8ac0b0fcada.png)

**Comment by travisghansen** [comment]
Yeah it is. Notice it’s going over https not http.

**Comment by UPEngineer** [comment]
Yep, that was it. I thought since https was marked out, it was http. Put in https and it installed.

Sorry about that.

**Comment by travisghansen** [comment]
No problem! Enjoy!

**Comment by travisghansen** [comment]
The mark through the https means the browser does not trust the certificate FYI.
